import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, Clock3, Pencil, Plus, Trash2, UserPlus, Users, X } from 'lucide-react';
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, Input } from '../../components/ui/components';
import { useAuth } from '../../context/AuthContext';
import api, { CreateTrainingProgramDto, TrainingEnrollment, TrainingProgram } from '../../services/api';

const MANAGEMENT_ROLES = ['SUPER_ADMIN', 'CEO', 'HR'];
const VIEW_ROLES = ['SUPER_ADMIN', 'CEO', 'HR', 'FINANCE_MANAGER', 'IT_MANAGER', 'SALES_MANAGER', 'EMPLOYEE'];
const statusColors = { UPCOMING: 'warning', IN_PROGRESS: 'blue', COMPLETED: 'success' } as const;
const enrollmentLabel = (status: TrainingEnrollment['status']) => status.replace('_', ' ');

const getError = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback;
const getEnrollments = (enrollments: TrainingEnrollment[] | undefined) => Array.isArray(enrollments) ? enrollments : [];

const Modal = ({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) => (
  <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4">
    <Card className="w-full max-w-lg shadow-xl"><CardHeader className="flex flex-row items-center justify-between border-b pb-4"><CardTitle>{title}</CardTitle><button type="button" aria-label="Close dialog" onClick={onClose} className="text-slate-400 hover:text-slate-700"><X size={20} /></button></CardHeader><CardContent className="pt-5">{children}</CardContent></Card>
  </div>
);

const ProgramModal = ({ program, onClose, onSubmit, busy }: { program?: TrainingProgram; onClose: () => void; onSubmit: (data: CreateTrainingProgramDto) => Promise<void>; busy: boolean }) => {
  const [form, setForm] = useState<CreateTrainingProgramDto>({ title: program?.title ?? '', description: program?.description ?? '', trainer: program?.trainer ?? '', department: program?.department ?? '', startDate: program?.startDate?.slice(0, 10) ?? '', endDate: program?.endDate?.slice(0, 10) ?? '' });
  const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!form.title.trim() || !form.trainer.trim() || !form.department.trim() || !form.startDate || !form.endDate) { setError('Title, trainer, department, and dates are required.'); return; } try { await onSubmit({ ...form, title: form.title.trim(), description: form.description || '', trainer: form.trainer.trim(), department: form.department.trim() }); onClose(); } catch (err) { setError(getError(err, 'Failed to save training program')); } };
  return <Modal title={program ? 'Edit Training Program' : 'Create Training Program'} onClose={onClose}><form onSubmit={submit} className="space-y-4">{error && <p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<label className="block text-sm font-medium text-slate-700">Title *<Input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label className="block text-sm font-medium text-slate-700">Trainer *<Input value={form.trainer} onChange={(e) => setForm({ ...form, trainer: e.target.value })} /></label><label className="block text-sm font-medium text-slate-700">Department *<Input value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-slate-700">Start Date *<Input type="date" value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} /></label><label className="block text-sm font-medium text-slate-700">End Date *<Input type="date" value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} /></label></div><label className="block text-sm font-medium text-slate-700">Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={4} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? 'Saving...' : program ? 'Save Changes' : 'Create Program'}</Button></div></form></Modal>;
};

const EnrollmentModal = ({ program, onClose, onSubmit, busy }: { program: TrainingProgram; onClose: () => void; onSubmit: (employeeIds: number[]) => Promise<void>; busy: boolean }) => {
  const [employees, setEmployees] = useState<any[]>([]); const [selected, setSelected] = useState<number[]>([]); const [error, setError] = useState('');
  useEffect(() => { api.getAllEmployees().then((response) => { const data = response?.data ?? response; setEmployees(Array.isArray(data) ? data : []); }).catch((err) => setError(getError(err, 'Failed to load employees'))); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!selected.length) { setError('Select at least one employee.'); return; } try { await onSubmit(selected); onClose(); } catch (err) { setError(getError(err, 'Failed to enroll employees')); } };
  return <Modal title={`Enroll employees: ${program.title}`} onClose={onClose}><form onSubmit={submit} className="space-y-4">{error && <p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="max-h-64 space-y-2 overflow-y-auto">{employees.map((employee) => { const id = Number(employee.id); const name = employee.name || `${employee.firstName ?? ''} ${employee.lastName ?? ''}`.trim() || employee.email; return <label key={id} className="flex items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" checked={selected.includes(id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, id] : current.filter((item) => item !== id))} />{name}<span className="ml-auto text-xs text-slate-400">{employee.email}</span></label>; })}</div><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? 'Enrolling...' : 'Enroll Employees'}</Button></div></form></Modal>;
};

const Training = () => {
  const { user } = useAuth(); const canManage = Boolean(user && MANAGEMENT_ROLES.includes(user.role));
  const [programs, setPrograms] = useState<TrainingProgram[]>([]); const [tab, setTab] = useState<'all' | 'mine'>('all'); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [modal, setModal] = useState<'program' | 'enroll' | null>(null); const [editing, setEditing] = useState<TrainingProgram>(); const [enrolling, setEnrolling] = useState<TrainingProgram>();
  const fetchPrograms = async () => { setLoading(true); setError(''); try { const data = await api.getTrainingPrograms(); setPrograms(Array.isArray(data) ? data : []); } catch (err) { setError(getError(err, 'Failed to load training programs')); } finally { setLoading(false); } };
  useEffect(() => { void fetchPrograms(); }, []);
  const mutate = async (action: () => Promise<void>, message: string) => { setBusy(true); setError(''); setSuccess(''); try { await action(); setSuccess(message); } catch (err) { setError(getError(err, 'Training action failed')); throw err; } finally { setBusy(false); } };
  const saveProgram = (data: CreateTrainingProgramDto) => mutate(async () => { const saved = editing ? await api.updateTrainingProgram(editing.id, data) : await api.createTrainingProgram(data); setPrograms((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [...current, saved]); }, editing ? 'Training program updated successfully' : 'Training program created successfully');
  const deleteProgram = (id: number) => { if (!window.confirm('Are you sure you want to delete this training program?')) return; void mutate(async () => { await api.deleteTrainingProgram(id); setPrograms((current) => current.filter((item) => item.id !== id)); }, 'Training program deleted successfully').catch(() => undefined); };
  const enroll = (selectedEmployeeIds: number[]) => mutate(async () => { const payload = { trainingProgramId: Number(enrolling!.id), employeeIds: selectedEmployeeIds.map((id) => Number(id)) }; await api.enrollEmployees(payload); await fetchPrograms(); }, 'Employees enrolled successfully');
  const complete = (enrollment: TrainingEnrollment) => mutate(async () => { const updated = await api.updateEnrollmentStatus(enrollment.id, { status: 'COMPLETED' }); setPrograms((current) => current.map((program) => ({ ...program, enrollments: getEnrollments(program.enrollments).map((item) => item.id === updated.id ? updated : item) }))); }, 'Training marked as complete').catch(() => undefined);
  const myPrograms = useMemo(() => programs.filter((program) => getEnrollments(program.enrollments).some((enrollment) => String(enrollment.employeeId) === String(user?.employeeId ?? user?.id))), [programs, user]);
  const ongoing = programs.filter((program) => program.status === 'IN_PROGRESS').length; const completed = programs.filter((program) => program.status === 'COMPLETED').length;
  if (loading) return <div className="p-8 text-center text-slate-500">Loading training programs...</div>;
  if (!VIEW_ROLES.includes(user?.role ?? '')) return <div className="p-8 text-center text-slate-500">Access Denied.</div>;
  return <div className="p-6 md:p-8 max-w-7xl mx-auto space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-slate-900">Training</h1><p className="text-sm text-slate-500">Build skills and track learning progress</p></div>{canManage && <Button onClick={() => { setEditing(undefined); setModal('program'); }}><Plus size={16} className="mr-2" />Create Training Program</Button>}</div>{error && <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}{success && <p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{success}</p>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat title="Total Training Sessions" value={programs.length} icon={<CalendarDays size={18} />} /><Stat title="Ongoing Sessions" value={ongoing} icon={<Clock3 size={18} />} /><Stat title="Completed Sessions" value={completed} icon={<CheckCircle2 size={18} />} /><Stat title="My Assigned Trainings" value={myPrograms.length} icon={<Users size={18} />} /></div><div className="flex gap-1 border-b border-slate-200"><button className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab === 'all' ? 'border-blue-600 text-blue-700' : 'border-transparent text-slate-500'}`} onClick={() => setTab('all')}>All Programs ({programs.length})</button><button className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab === 'mine' ? 'border-blue-600 text-blue-700' : 'border-transparent text-slate-500'}`} onClick={() => setTab('mine')}>My Trainings ({myPrograms.length})</button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{(tab === 'all' ? programs : myPrograms).map((program) => <ProgramCard key={program.id} program={program} canManage={canManage} busy={busy} onEdit={() => { setEditing(program); setModal('program'); }} onDelete={() => deleteProgram(program.id)} onEnroll={() => { setEnrolling(program); setModal('enroll'); }} onComplete={complete} userId={user?.employeeId ?? Number(user?.id)} />)}{(tab === 'all' ? programs : myPrograms).length === 0 && <Card className="md:col-span-2 xl:col-span-3"><CardContent className="py-12 text-center text-sm text-slate-500">{tab === 'mine' ? 'No assigned trainings yet.' : 'No training programs found.'}</CardContent></Card>}</div>{modal === 'program' && <ProgramModal program={editing} onClose={() => { setModal(null); setEditing(undefined); }} onSubmit={saveProgram} busy={busy} />}{modal === 'enroll' && enrolling && <EnrollmentModal program={enrolling} onClose={() => { setModal(null); setEnrolling(undefined); }} onSubmit={enroll} busy={busy} />}</div>;
};

const Stat = ({ title, value, icon }: { title: string; value: number; icon: React.ReactNode }) => <Card><CardContent className="flex items-center justify-between p-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div><div className="rounded-lg bg-blue-50 p-3 text-blue-600">{icon}</div></CardContent></Card>;

const ProgramCard = ({ program, canManage, busy, onEdit, onDelete, onEnroll, onComplete, userId }: { program: TrainingProgram; canManage: boolean; busy: boolean; onEdit: () => void; onDelete: () => void; onEnroll: () => void; onComplete: (enrollment: TrainingEnrollment) => void; userId: number }) => {
  const enrollments = getEnrollments(program.enrollments);
  const enrollment = enrollments.find((item) => String(item.employeeId) === String(userId));
  const count = program.enrolledCount ?? enrollments.length;
  return <Card><CardHeader className="flex flex-row items-start justify-between"><div><CardTitle className="text-base">{program.title}</CardTitle><p className="mt-1 text-sm text-slate-500">{program.trainer}</p></div><Badge variant={statusColors[program.status]}>{program.status.replace('_', ' ')}</Badge></CardHeader><CardContent className="space-y-3 pt-2"><div className="flex items-center justify-between"><Badge variant="blue">{program.department}</Badge><span className="text-xs text-slate-500">{count} enrolled</span></div><p className="text-sm text-slate-600">{program.description || 'No description provided.'}</p><p className="flex items-center gap-1 text-xs text-slate-500"><CalendarDays size={13} />{new Date(program.startDate).toLocaleDateString()} - {new Date(program.endDate).toLocaleDateString()}</p>{canManage && <div className="flex flex-wrap gap-2 border-t border-slate-100 pt-3"><Button size="xs" variant="outline" onClick={onEdit}><Pencil size={12} className="mr-1" />Edit</Button><Button size="xs" variant="outline" onClick={onEnroll}><UserPlus size={12} className="mr-1" />Enroll</Button><button type="button" aria-label={`Delete ${program.title}`} onClick={onDelete} disabled={busy} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50 disabled:opacity-50"><Trash2 size={15} /></button></div>}{enrollment && <div className="border-t border-slate-100 pt-3"><div className="flex items-center justify-between text-xs text-slate-500"><span>Your status: {enrollmentLabel(enrollment.status)}</span>{enrollment.status !== 'COMPLETED' && <Button size="xs" onClick={() => onComplete(enrollment)} disabled={busy}>Mark as Complete</Button>}</div></div>}{canManage && <div className="mt-3 border-t pt-2 text-xs text-gray-600"><span className="mb-1 block font-semibold">Enrolled staff:</span><div className="flex flex-wrap gap-1">{enrollments.length > 0 ? enrollments.map((item) => <span key={item.id} className="rounded-full border border-blue-200 bg-blue-50 px-2 py-0.5 text-[11px] text-blue-700">{item.employee?.firstName ? `${item.employee.firstName} ${item.employee.lastName || ''}` : item.employeeName || `Employee #${item.employeeId}`}</span>) : <span className="text-gray-400 italic">No staff enrolled yet</span>}</div></div>}</CardContent></Card>;
};

export default Training;